/// <reference lib="webworker" />

/**
 * Custom Service Worker for Iron Track.
 *
 * Generated by vite-plugin-pwa via the injectManifest strategy. It does the
 * same precaching + navigation fallback as the previous generateSW config,
 * PLUS handles real Web Push events sent from the Cloudflare Worker so
 * supplement reminders arrive when the app is fully closed.
 */

import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<{ revision: string | null; url: string }>;
};

self.skipWaiting();
cleanupOutdatedCaches();

precacheAndRoute(self.__WB_MANIFEST);

// Navigation fallback — serve index.html for SPA routes (e.g. HashRouter
// initial loads on github.io).
registerRoute(new NavigationRoute(createHandlerBoundToURL('index.html')));

// Asset caching tiers (matches what we had under generateSW).
registerRoute(
  ({ request }) =>
    request.destination === 'style' ||
    request.destination === 'script' ||
    request.destination === 'worker',
  new StaleWhileRevalidate({ cacheName: 'assets' }),
);

registerRoute(
  ({ request }) => request.destination === 'document',
  new NetworkFirst({ cacheName: 'pages', networkTimeoutSeconds: 3 }),
);

registerRoute(
  ({ request }) => request.destination === 'image' || request.destination === 'font',
  new CacheFirst({
    cacheName: 'static-resources',
    plugins: [new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  }),
);

// ===========================================================================
// Push handling
// ===========================================================================

interface PushPayload {
  title?: string;
  body?: string;
  tag?: string;
  data?: { url?: string } & Record<string, unknown>;
}

self.addEventListener('push', (event) => {
  let data: PushPayload = {};
  if (event.data) {
    try {
      data = event.data.json() as PushPayload;
    } catch {
      data = { title: 'Iron Track', body: event.data.text() };
    }
  }
  const title = data.title ?? 'Iron Track';
  event.waitUntil(
    self.registration.showNotification(title, {
      body: data.body,
      icon: '/icons/icon-192.png',
      badge: '/icons/icon-192.png',
      tag: data.tag,
      data: data.data,
      // Always show — iOS PWA enforces visible notifications anyway.
      requireInteraction: false,
    } as NotificationOptions),
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const targetPath = (event.notification.data as { url?: string } | undefined)?.url ?? '/';
  // For HashRouter we use a hash route; resolve relative to the SW scope.
  const url = new URL(targetPath, self.registration.scope).toString();
  event.waitUntil(
    (async () => {
      const all = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
      // Prefer focusing an existing window of ours.
      const existing = all.find((c) => c.url.startsWith(self.registration.scope));
      if (existing) {
        try {
          await (existing as WindowClient).navigate(url);
        } catch {
          /* navigate may reject if not same-origin; ignore */
        }
        return (existing as WindowClient).focus();
      }
      return self.clients.openWindow(url);
    })(),
  );
});

self.addEventListener('pushsubscriptionchange', (event) => {
  // The browser rotated our subscription. The client will see this on next
  // load via pushManager.getSubscription() and re-sync to the backend.
  // We don't have credentials in the SW to do it ourselves.
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((all) => {
      for (const c of all) c.postMessage({ type: 'iron-track:pushsubscriptionchange' });
    }),
  );
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
